### ISSUE TITLE
Usage in Angular

### ISSUE THREAD

**Issue by kadirmaev** [shaack/cm-chess#3]
Hi! Im trying to add this library to my work project (we already use cm-chessboard) and face an issue:
Default Angular compiler do not recognize the module. Even if I add custom .d.ts file to declare non-typescript module. 
The reeson seems to be in package.json in line
```
"main": "index.html"
```
If I replace it with 
```
"main": "./src/cm-chess/Chess.js"
```
then all is OK. Can you fix this?

**Comment by kadirmaev** [comment]
I created PR for this, if interested https://github.com/shaack/cm-chess/pull/4

**Comment by shaack** [comment]
Thanks, I published it with Version 2.1.7
